name: CI

on:
  push:
    branches: [main]
    paths:
      - "**.asm"
      - ".github/workflows/ci.yml"
  pull_request:
    branches: [main]
    paths:
      - "**.asm"
      - ".github/workflows/ci.yml"

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # https://github.com/actions/runner-images?tab=readme-ov-file#available-images
        os: [macos-latest, macos-15-intel, ubuntu-slim]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install NASM on macOS
        if: runner.os == 'macOS'
        run: brew install nasm

      - name: Install NASM on Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y nasm libncurses-dev

      - name: Build
        run: make
        shell: bash
